name: getgems-async-bot
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    command: python3 manage.py run-stats-fetcher
    networks:
      - my_super_network

networks:
  my_super_network:
    external: true
